# Generated by Django 4.1.3 on 2022-11-17 20:05

import django.core.validators
from django.db import migrations, models
import project.models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_alter_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='aplication',
            name='comment',
            field=models.CharField(blank=True, max_length=250, verbose_name='Комментарий'),
        ),
        migrations.AddField(
            model_name='aplication',
            name='second_photo',
            field=models.ImageField(null=True, upload_to=project.models.get_name_file, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg', 'bmp']), project.models.validate_image_size]),
        ),
    ]
