# Generated by Django 4.1.3 on 2022-11-14 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_alter_user_lname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('3d', '3-D Дизайн'), ('2d', '2-D Дизайн'), ('sketch', 'Эскиз')], max_length=250, verbose_name='Название'),
        ),
    ]
