# Generated by Django 4.1.3 on 2022-11-17 20:52

import django.core.validators
from django.db import migrations, models
import project.models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_aplication_comment_aplication_second_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aplication',
            name='second_photo',
            field=models.ImageField(blank=True, null=True, upload_to=project.models.get_name_file, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg', 'bmp']), project.models.validate_image_size]),
        ),
    ]
