# Generated by Django 4.1.3 on 2022-11-14 13:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_user_personal_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='aplication',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата заявки'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aplication',
            name='status',
            field=models.CharField(choices=[('new', 'Новая'), ('done', 'Выполнено'), ('received', 'Принято в работу')], default='New', max_length=250, verbose_name='Статус'),
        ),
    ]
